# name: Simple url check
on: [push]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        babashka-url: ['https://github.com/babashka/babashka/releases/download/v1.1.172/babashka-1.1.172-linux-amd64-static.tar.gz']
    steps:
      - name: Setup Babashka
        id: setup-babashka
        uses: turtlequeue/setup-babashka@main
        with:
          babashka-version: 1.1.172
          babashka-url: ${{ matrix.babashka-url }}

      - name: Check if bb runs fine
        run: bb --version

      - name: Setup Babashka from cache
        id: setup-babashka-2
        uses: turtlequeue/setup-babashka@main
        with:
          babashka-version: 1.1.172
          babashka-url: ${{ matrix.babashka-url }}

      - name: Check if bb runs fine from cache
        run: bb --version
  check-windows:
    # https://ci.appveyor.com/project/borkdude/babashka
    runs-on: windows-latest
    strategy:
      matrix:
        babashka-url: ['https://ci.appveyor.com/api/buildjobs/jem1nge8xapaubv6/artifacts/babashka-1.3.183-SNAPSHOT-windows-amd64.zip']
    steps:
      - name: Setup Babashka
        id: setup-babashka
        uses: turtlequeue/setup-babashka@main
        with:
          babashka-version: 1.1.173-SNAPSHOT
          babashka-url: ${{ matrix.babashka-url }}

      - name: Check if bb runs fine
        run: bb --version

      - name: Setup Babashka from cache
        id: setup-babashka-2
        uses: turtlequeue/setup-babashka@main
        with:
          babashka-version: 1.1.173-SNAPSHOT
          babashka-url: ${{ matrix.babashka-url }}

      - name: Check if bb runs fine from cache
        run: bb --version
